spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/studydb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
app:
  email:
    fromAddress: zhengwei_0125@126.com
    username: zhengwei_0125@126.com
    password: ZHengWei@1210
    smtpHost: smtp.126.com
